### ISSUE TITLE
"Resuming" CSV after a pause doesn't work

### ISSUE THREAD

**Issue by missmaggieha** [CDOT-EDX/Project#101]
See "Maggie's Test Module -> Bugs -> Snap 9 - Resume CSV doesn't work"

**Comment by pkuzhel** [comment]
Which slidei is this @missmaggieha ?

**Comment by missmaggieha** [comment]
@pkuzhel if you go to my test module. I made a section called bugs. Both those units in bugs need to be implemented in snap 9, slide 3-4. The unit will demonstrate the error correspondingly.

**Comment by pkuzhel** [comment]
Hmm seems like this is only an issue if there is no more content and CSV needs to be resumed.

Here is what I tried and it seemed to work, I've added another slideContent at the end with media CSV and I've entered as the line number, the last/second last row of the csv:

```
        {
            "content": 
            {
                "html": "<p class=\"placeholderText\">The CSV should be resuming now!</p><p>If you see a problem, click on the instrument indicating it.</p>"  
            },

            "media": {
                "type": "button",
                "index": 2
            },

            "action": {
                "type": "play",
                "index": 2,
                "line": 291
            }
        },
        {
            "content":{ 
              "html": "CSV Finished",
              "action": "append" 
            },
            "media": {
                "type": "csv",
                "index": 2,
                "line": 800
            },
        }
```

and CSV resumes fine and fires the end event as well.

**Comment by missmaggieha** [comment]
Thanks!
