### ISSUE TITLE
Remediation text from previous quiz on slide shows up in later quiz

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#116]
Remediation text and/or "OK, now let's look at what options show:" title show up multiple times when completing multiple quizzes in one slide.

Example on Snap 7 Slide 17 (Unit 8)
![remediation](https://cloud.githubusercontent.com/assets/3028095/11159254/f49a80b2-8a2b-11e5-8eff-10f48e1a97a1.jpg)

**Comment by missmaggieha** [comment]
Looks like all slides that have the two quizzes, this problem can occur.
Example see Release Snap6, slide 15-18.Spot the Anomaly 4. 

FYI: Correct instruments = ALT or VSI, Quiz 1 option 1, Quiz 2, option 3
FYI: What should happen, Quiz 1, if incorrect, retry/redo, else is correct - show remediation go to quiz 2
FYI: Quiz 2, doesn't matter if correct or incorrect, will show remediation.

Problems:
Use case: Correct instrument, correct quiz 1, correct quiz 2. --- Both remediation shows up after quiz 2. (should only show remediation of Quiz 2)

Use case: Correct instrument, incorrect quiz 1 -- retry, correct instrument, correct quiz 1, correct quiz 2 (same as above, both remediation shows)

No console errors
