### ISSUE TITLE
SlideEnd for Quizzes

### ISSUE THREAD

**Issue by missmaggieha** [CDOT-EDX/Project#130]
See Maggie's Test Modules -> Snap 4 -> Terminology (Slide 4)

**Comment by missmaggieha** [comment]
SlideEnd in general actually.

**Comment by pkuzhel** [comment]
slideEnd works but a "play" event gets fired after the end and changes the "status" of the slide. If "autoRedirect" is true, this isn't visible but should be fixed for the case of no 'autoRedirect'

**Comment by missmaggieha** [comment]
@pkuzhel This needs to be fixed. Scanning of the instruments in the correct scanning pattern, with a quiz with each scanned instrument. After the last quiz (from clicking on the turn coordinator), it doesn't advance to the next slide content (begin auto redirect) Snap 4, slide Terminology.

**Comment by pkuzhel** [comment]
theres a bigger issue here than slideEnd, I need to look into why quiz 7 shows for quiz 8
