### ISSUE TITLE
Quizzes - onFail conditions

### ISSUE THREAD

**Issue by missmaggieha** [CDOT-EDX/Project#133]
There are some quizzes where it is a true or false quiz, where if you get the question wrong, you will be shown the remediation and move on to the next question. Currently this option to continue is not available. 

Snap 5, Slide 25.

**Comment by pkuzhel** [comment]
As discussed, could be solved with the new option on quizzes: attemptsBeforeRemediation

**Comment by pkuzhel** [comment]
fixed.
