### ISSUE TITLE
Media highlight is not working correctly. Snap 5, Slide 26

### ISSUE THREAD

**Issue by missmaggieha** [CDOT-EDX/Project#134]
Media highlight is not working correctly. Snap 5, Slide 26. All six panel highlights are enabled, if you click the correct one, it should display the slideContent associated with that highlight. However, currently, it just displays the next immediate slideContent.

**Comment by pkuzhel** [comment]
Fixed this by using onSuccess and onFail... have a highlight as a media doesn't actually trigger the proper slideContent but does avoid having to have audio/csv as a media
