### ISSUE TITLE
Quizzes - Incorrect answer however displays both "Correct" and "IncorrectMaxAttempts" messages

### ISSUE THREAD

**Issue by missmaggieha** [CDOT-EDX/Project#135]
See Maggie's Test Module -> Snap 9 (REV) -> Slide 3-5.

Quiz: "attemptsBeforeRemediation" = 1, 
Selected incorrect answer and it will displays both "Correct" and "Incorrect Max Message".

Perhaps "Correct" quiz from previous attempts were not cleared?

**Comment by pkuzhel** [comment]
fixed
