### ISSUE TITLE
Back and Continue for EDX quiz...

### ISSUE THREAD

**Issue by echanna** [CDOT-EDX/Project#33]
Slides are currently supporting the idea of forwarding or rewinding to the id of the Lesson Unit.  The EDX default QUIZ does not support this much needed feature.  It is a good idea now to add this to the default EDX Quiz.

**Comment by pkuzhel** [comment]
I believe our goal is to use createSlide in combination with slickQuiz and Raymond's ComplexHTML Xblock in order to handle quizzes

**Comment by pkuzhel** [comment]
Using slickQuiz inside createSlide to address this
