### ISSUE TITLE
Do we need remediation displayed for Quizzes? Success and Failure callbacks!

### ISSUE THREAD

**Issue by echanna** [CDOT-EDX/Project#47]
Are the students suppose to be able to receive remediation?  If so there are callbacks available.  These callbacks need to be wrapped as a string for the JSON object.

**Comment by Markieta** [comment]
+1 remediation text still needs to be displayed when enabled to do so.

**Comment by pkuzhel** [comment]
yep, still a bug which needs to be fixed

**Comment by glengal** [comment]
fixed
