### ISSUE TITLE
Anomaly 4:  Multiple Highlights can be correct

### ISSUE THREAD

**Issue by echanna** [CDOT-EDX/Project#51]
This exercise is different because there are two highlights that are either correct.  So the student can advance through the slide in two different ways.

**Comment by pkuzhel** [comment]
Hmm interesting use case. I will make sure to allow an array of indices and will update when it is completed

**Comment by Markieta** [comment]
+1 Has this been implemented yet? It doesn't seem to work.

**Comment by pkuzhel** [comment]
Not implemented yet, usually I would try to close the issue (when I remember). Still in the works

**Comment by pkuzhel** [comment]
Should be implemented now with the new advanceWith ability

**Comment by Markieta** [comment]
Can you specify an array of advanceWith's yet (different types)?

**Comment by CDOT-EDX** [comment]
Yep, should work.

But keep in mind that both a highlight and a button (if those are the types specified) will be correct for the array of indices. I don't differentiate the index for one or another although I probably should. Let me know if this will be needed at all for a use case.

From: Christopher Markieta
Sent: Thursday, September 24, 2015 18:02
To: CDOT-EDX/Project
Reply To: CDOT-EDX/Project
Subject: Re: [Project] Anomaly 4: Multiple Highlights can be correct (#51)

Can you specify an array of advanceWith's yet (different types)?

##

**Comment by pkuzhel** [comment]
I am not sure how me replying from my e-mail makes me look like I am CDOT-EDX as a user :S

**Comment by Markieta** [comment]
I had a feeling it was you. :smile: 

I was thinking of something more like this: 

``` json
"advanceWith":
[
    {
        "type": "highlight",
        "index": 1
    },
    {
        "type": "csv",
        "index": 0,
        "line": 225
    }
]
```

This way you avoid complications as you mentioned above, and it's a lot clearer. Things might go wrong if a button is looking for a line number. :persevere:

**Comment by pkuzhel** [comment]
Haha good point. I am not sure about the CSV use case, that wouldn’t work even now (CSV doesn’t fire an event every time it switches a line, but it could). However allowing advanceWith to be an array could work and it does look pretty clean. Let me give it some thought.
