### ISSUE TITLE
CSVs have a few edge cases where they fail

### ISSUE THREAD

**Issue by pkuzhel** [CDOT-EDX/Project#62]
Edward,

If it is possible, look through the CSVs from Snap4-6 once more and check to make sure that they are all saved in the proper format CSV not OTD.

Make sure the headers are gone, that the CSVs work on online.cdot (make a generic slide with CSV being the first and only media).

Also check the last or second last line of the CSV and make sure that all of the columns have a value... at some point my instruments go crazy in the last line or two because some values are missing. If this is the case just delete the last 10-20 lines.

Also, delete the 100-200/300 first lines where nothing happens for some of the CSVs (might not be the case for all CSVs).
Meaning, the CSVs that show take-off, have nothing happening up until about 10 seconds into the animation. We can probably look at the airspeed data inside the csv to detect when it starts to change by looking at the airspeed values (8th column from the left i believe). Maybe leave about 15-20 lines before the actual airspeed value changes to give a bit of a stable buffer to the students. We can check how it looks once you've done or two CSVs.

Thanks!

**Comment by echanna** [comment]
OK, I reviewed the CSVs from 4,5,6 and found relative changes and re-uploaded.  You will see these files in the most recently uploaded. Your welcome.
