### ISSUE TITLE
remove the "options" object from slides

### ISSUE THREAD

**Issue by pkuzhel** [CDOT-EDX/Project#67]
Edward,

I think I've made a mistake in telling you how to form the "options" JSON object to pass it on to createSlide.

We do not need to define an "options" object inside of the JSON, we can leave all those parameters on the same level as slideContent and mediaFiles.

We will talk more once you want to take a look at this

**Comment by echanna** [comment]
Yes, I may have not noticed a slide while converting to the new format you mentioned. Thanks

**Comment by pkuzhel** [comment]
Since we've had good practice with making proper json objects yesterday let's hope we can convert them all properly. Should we keep the issue as a reminder or can we close it @echanna ?
