### ISSUE TITLE
Call a new flight from onSucces of parent Quiz.

### ISSUE THREAD

**Issue by echanna** [CDOT-EDX/Project#69]
For example, Slide 15 of the SNAP7 specs require that the panel start over with a new flight when the student gets the quiz question right.

**Comment by echanna** [comment]
This flight plan may need to be submitted to our Project Pilot

**Comment by pkuzhel** [comment]
I believe they 'continue' the flight and we just swap the csv to make it seems as the flight is continued.

However, I am working on this and this should be finished by tomorrow
