### ISSUE TITLE
Pause animation based on Quiz

### ISSUE THREAD

**Issue by echanna** [CDOT-EDX/Project#73]
The user needs to click a highlight an area on the panel and do a quiz based on the right highlight.  So I do one slide content for the animation and highlight.  That slide content advances based on the right index been clicked.  The slide advanced to has the Quiz.  What if the student clicks the wrong answer?  The specs outline that we need to pause the animation.

**Comment by Markieta** [comment]
+1 Need the ability to pause and resume CSV animations (see M03S08_Slide6-7).

**Comment by pkuzhel** [comment]
Is the solution that I described earlier not sufficient?

If the use of this feature is only required for two slides, I would solve the issue by extending the CSV with a few hundred of static lines (keeping the values the same) acting as a Pause and a Timer at the same time, once a certain line is reached and the user hasn't interacted, we can let them know about it.

We can do most of this by using attaching a slideContent to a CSV media type with a line index.

What do you think @Markieta ?

**Comment by Markieta** [comment]
This method does not work for content that requests the user to press a "Resume" button before continuing. If we can change the intended implementation, I'm all for that.

**Comment by pkuzhel** [comment]
Once I have an opportunity to check out the Snap 8 Slide 6-7, I'll let you know.

**Comment by pkuzhel** [comment]
I hope this helps. I've added ability to pause audio and csvs. Example is in the README at here just to be safe:

```
    // PAUSE / PLAY example for CSV
    {
        "media":{
            "index": 2,
            "type": "csv",
            "line": 1000,
        },
        "action": {
          "type": "pause",
          "index": 2
        },
        "advanceWith": {
            "type": "button",
            "index": 1
        },
    },
    {
        "media": {
          "type": "button",
          "index": 1
        },
        "action":{
          "type": "play",
          "index": 2 // can only be a mediaIndex (not contentIndex)
          "line": 1001 // in this case its a csv
          // in the case of an audio we can specify "second": 10.1 and not 'line'
        }
    },
    // PAUSE / PLAY example for AUDIO
    {
        "media":{
            "index": 2,
            "type": "audio",
            "second": 7,
        },
        "action": {
          "type": "pause",
          "index": 2
        },
        "advanceWith": {
            "type": "button",
            "index": 1
        },
    },
    {
        "media": {
          "type": "button",
          "index": 1
        },
        "action":{
          "type": "play",
          "index": 2 // can only be a mediaIndex (not contentIndex)
          "second": 7.1 // in this case its an audio
        }
    }
```
