### ISSUE TITLE
Implement logic for content creation

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#81]
To display different `slideContent` depending on the result of the `if(condition)`

Example: Show warning text if 15 seconds elapse before the user selects the correct highlight (see M03S08_Slide8).

**Comment by pkuzhel** [comment]
I'm working on this right now, it will be the `onSuccess` and `onFail` objects inside an `advanceWith`

**Comment by pkuzhel** [comment]
This functionality is available for use, refer to the README
