### ISSUE TITLE
Sequential playback of CSV

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#82]
A unit should be able to play multiple CSVs sequentially. This still doesn't seem to work.

**Comment by pkuzhel** [comment]
Should work, can you reference as Snap+Slide that I can take a look at?

**Comment by Markieta** [comment]
Here is a test example using 7.1.csv and 7.2.csv. For some reason it only animates 7.2.csv.

https://online.cdot.senecacollege.ca/courses/Seneca_College/M01S01_Test/2014_Winter/courseware/9b0c09c0f65d4e72803bc7b71a57a19f/19eee716bb2f48b2b80199a197d4efd3/1

**Comment by pkuzhel** [comment]
Yep you're right. I have a scope issue in this piece of code. Working on resolving it!

**Comment by pkuzhel** [comment]
You're right! Thanks for pointing it out. I have a huge scope issue here that I haven't noticed until now. Working on it now

**Comment by pkuzhel** [comment]
Give this a try now, seems like after a few hours I got it!

**Comment by Markieta** [comment]
Yup, works now. Thanks!
