### ISSUE TITLE
Add the ability to repeat quiz question

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#83]
To force the user to continue guessing until the correct answer is selected.

For example: Asking for the clearance to be repeated (see M03S07_Slide7-8).

**Comment by pkuzhel** [comment]
We can assign custom content events to buttons and highlights. Maybe I could add a way to specify a mediaIndex to jump to once the button is pressed

**Comment by pkuzhel** [comment]
has been implemented. refer to README or Snaps 6/7
