### ISSUE TITLE
Implement timer for user interaction

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#84]
A timer is required to measure a user's agility to interact with the panel.

User must select button between specified time frame (see M03S07_Slide10).

**Comment by pkuzhel** [comment]
I will be attempting to run timer tests sometime this week. Thanks!

**Comment by glengal** [comment]
I'll work on this bug

**Comment by pkuzhel** [comment]
Refer to README to see the usage of timer. Should work fairly well
