### ISSUE TITLE
Callbacks not being executed

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#86]
It seems like callback functions are loaded in as object but are not actually running.

Is there a specific way to call callbacks? Or should they be executed once present in the slide? The example console.log functions only store an object in the markup, but does not actually print anything to the console.

Formatting also looks broken:

![callback-error](https://cloud.githubusercontent.com/assets/3028095/10085714/b17185da-62d8-11e5-9126-a75d83455f9b.jpg)

Example: https://online.cdot.senecacollege.ca/courses/Seneca_College/M01S01_Test/2014_Winter/courseware/9b0c09c0f65d4e72803bc7b71a57a19f/19eee716bb2f48b2b80199a197d4efd3/2

**Comment by CDOT-EDX** [comment]
Aaa there we go. Was wondering how it magically still worked cause nobody has mentioned it. Thanks!  What happened was that when we used to init createSlide from within a script tag, we never had to wrap all properties key value pairs in strings/quotations. Now with the xblock we are forced to have proper JSON and once I have the variable of the function inside the library, it is still a string.

Anyway, I'll try to fix this asap. Which slide is this on?

From: Christopher Markieta
Sent: Thursday, September 24, 2015 16:27
To: CDOT-EDX/Project
Reply To: CDOT-EDX/Project
Subject: [Project] Callbacks not being executed (#86)

It seems like callback functions are loaded in as object but are not actually running.

Is there a specific way to call callbacks? Or should they be executed once present in the slide? The example console.log functions only store an object in the markup, but does not actually print anything to the console.

Formatting also looks broken:

[callback-error]https://cloud.githubusercontent.com/assets/3028095/10085714/b17185da-62d8-11e5-9126-a75d83455f9b.jpg

##

**Comment by Markieta** [comment]
I was just playing around with it in "Chris' Test Module/Test/Aircraft Animation" using the following:

``` json
{
    "slideContent":
    [
        {
            "title": {"html": "Aircraft Animation"},
            "callback": "function(){ console.log('You did smth right'); }"
        }
    ]
}
```

**Comment by pkuzhel** [comment]
Have you had time to work on this @Markieta or can I try and resolve it?

**Comment by Markieta** [comment]
I have not started working on this yet.

**Comment by pkuzhel** [comment]
should be fixed. functions should be wrapped in brackets: 
ie: "slideContent": [ "callback": "(function(){ console.log('this is a test');})" ]
