### ISSUE TITLE
Audio doesn't play when panel is enabled and no CSV is present

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#87]
Audio fails to play when the instrument panel is enabled and there is no CSV in mediaFiles.

Needed for explaining the instrument panel only (see M01S01_Slide9).

Workaround: Using a fake CSV file.

**Comment by pkuzhel** [comment]
Have you tried using the "noCSV": true, inside the JSON options?

**Comment by Markieta** [comment]
Oh right, forgot about that!
