### ISSUE TITLE
AdvanceWith for Quizzes

### ISSUE THREAD

**Issue by missmaggieha** [CDOT-EDX/Project#88]
The ability to advance to the next 'slideContent' after a quiz is complete (including any remediation texts or conditionals).

Also if a quiz is being displayed with a media (audio, csv), the quiz will be skipped to the next 'slideContent' the moment the media is complete.

**Comment by pkuzhel** [comment]
I've implemented the quiz "end" event now (it doesn't consider correct / incorrect responses yet, that will come with conditionals)

In terms of it being skipped if audio is playing. We need to make sure to set "advanceWith": { "type": "quiz", "index": 0 } to make sure that we wait for the correct input from quiz to proceed with content

I noticed that the quiz behaves a bit strange on Snap 7 Slide 6-11, let's try to set up a quick skype or TeamViewer call to chat quickly about options available for quizzes.

Thanks!
