### ISSUE TITLE
Fix modal implementation

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#91]
Modal instrument zooming does not seem to work. May need to be fixed or reimplemented.

**Comment by Markieta** [comment]
Working: 
![modal](https://cloud.githubusercontent.com/assets/3028095/10958377/4ec950b0-833b-11e5-8f74-e49935f893f4.jpg)

Still need to support adding buttons to modal.

**Comment by pkuzhel** [comment]
@Markieta is there a way to fix that gap between the header and the body of the modal?

I haven't looked into your updated code too much, looked all good to me but bootstrap modals do no have a break in between: http://getbootstrap.com/javascript/#live-demo

Could it be that they are two different modals in your fix?

![bootstram_modal](https://cloud.githubusercontent.com/assets/5421417/11066659/160d07b6-8797-11e5-951f-24418659077a.png)

**Comment by Markieta** [comment]
I'm not sure why there was a gap originally but I can look into it. Also
need to update the rotation of the modal in realtime to correlate with the
original.

**Comment by pkuzhel** [comment]
The modal is just a container really, no need to rotate it. I think you mean to make sure that the instrument is animated.

From what I remember from the storyboards, the instruments are not dynamic at that point of the course yet and the instrument will only be animated on pressing the buttons which should be inside the modal. It will required some work but let's get the modals to show up properly first.

**Comment by pkuzhel** [comment]
@Markieta please study my updated code for modals, I commented out your changes in buildContent and I tried to make sure we can do everything without changing any of the code that is already there. Most of this functionality is present. As I have mentioned before, think of a modal as being a separate new createSlide object, all the features that are available to creating the whole slide should be working the same for a modal and this way we keep ourselves from creating repetitive code.

I've made sure that setupInnerContent depends on all of the options that are defined in buildModals. This is the approach we should try to stick to. Let me know if you have any questions after viewing my changes.

Thanks

**Comment by pkuzhel** [comment]
Majority of this functionality works. Granted there will need to be more fixes, work to make sure buttons work, highlights shouldn't be a huge problem.

Events on buttons and highlights will definitely need work as well, in the meantime closing this issue since basic Modals work
