### ISSUE TITLE
Implement ability to control panel or instrument via buttons

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#94]
Allow the user to demonstrate instrument activity through buttons.

Example: Provide "Pitch Up" and "Pitch Down" buttons that alter the pitch accordingly. (M01S01_Slide10)

**Comment by pkuzhel** [comment]
I've just added this feature in:
We can now specify a `mediaIndex` property on a button, which will either play an audio or a CSV.

CSV is mostly stable unless you click the same button twice or more (working on the fix)
and audio is still untested at this point

Syntax would be as following when declaring new buttons in the options

```
"buttons": [
        {"id": "off",
            "title": "Confirm OFF Flag"
        },
        {"id": "topple",
            "title": "TOPPLE",
         "mediaIndex": 3
        },
        {"id": "freeze",
            "title": "FREEZE",
         "mediaIndex": 4
        },
        {"id": "precess",
            "title": "PRECESS",
         "mediaIndex": 5
        }
    ]
```
