### ISSUE TITLE
Panel highlights are broken

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#96]
Highlighting of standard panel instruments no longer work.

See example from my test module: [M01S03_Slide2](https://online.cdot.senecacollege.ca:18010/container/i4x://Seneca_College/M01S01_Test/vertical/916f49e369ad49b386dcf0341ee13fcb)

**Comment by pkuzhel** [comment]
I see the highlights just fine on that slide. What exactly is the issue you're experiencing? @Markieta

**Comment by Markieta** [comment]
I am not seeing any highlights on either Chrome or Firefox.

**Comment by pkuzhel** [comment]
Have you tried clearing your cache? This is weird because I cleared my cache and works fine for me in Chrome. 
![screen shot 2015-10-15 at 21 17 40](https://cloud.githubusercontent.com/assets/5421417/10531634/4380082a-7382-11e5-843e-77ccbf887838.png)

**Comment by Markieta** [comment]
That did not fix it. :worried: The console proceeds to say it's trying to make button highlights, followed by some lines containing "undefined". I'll show you tomorrow.

Could it be that you have a certain extension installed to support this in JS?

**Comment by pkuzhel** [comment]
Nope, the `undefined` and other notes in the console were simply for debugging other issues I was having with specifying independent mediaIndices which you are most likely not using.

I have the highlights showing in all three of my browsers (FF, Safari and Chrome). Weird. Curious to see what the cause for this is on your machine.

**Comment by CDOT-EDX** [comment]
Hi Paul,

We have new requirements from Gordon. He needs to have snap 6 & 7 for demo
in a special course until FRIDAY Nov 18.
Please tell everyone that this is most important task, so that we can be
ready for his demo.

Thanks,
Jordan

On Wed, Nov 18, 2015 at 11:57 AM, Pavlo Kuzhel notifications@github.com
wrote:

> Closed #96 https://github.com/CDOT-EDX/Project/issues/96.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CDOT-EDX/Project/issues/96#event-468172543.

## 

Jordan Anastasiade
